services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -port 30333
    ports:
      - "30333:30333"
    working_dir: /home/dynamodblocal
