service: emptystream
frameworkVersion: "3"

plugins:
  - serverless-s3-local
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-prune-plugin

custom:
  serverless-offline:
    httpPort: 30330

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  region: us-east-1
  deploymentMethod: direct
  environment:
    SLS_STAGE: ${sls:stage}
    SERVICE_NAME: ${self:service}
    OFFLINE_S3_HOST: "localhost"
    OFFLINE_S3_PORT: "4569"
    OFFLINE_S3_PATH: ""
    OFFLINE_S3_PROTOCOL: "http:"

functions: ${file(serverless-functions.yml)}

resources:
  - ${file(serverless-resources.yml)}
